### ISSUE TITLE
failing @Test stopsBeforeToWhenEveryPeriodIsAfterEndDate()

### ISSUE THREAD

**Issue by cybernetics** [tginsberg/java-timestream#6]
https://github.com/tginsberg/java-timestream/blob/1e02ac00fa577c70d7d5b46179115324439244f0/src/test/java/com/ginsberg/timestream/LocalDateStreamTest.java#L188

![image](https://user-images.githubusercontent.com/79887/42251782-2e4652d2-7eee-11e8-970b-572be38303a2.png)

**Comment by tginsberg** [comment]
Thanks for finding this. Pretty sure this is just a test issue (looks like I'm incorrectly setting up the test, given its name). I'll fix this.

**Comment by tginsberg** [comment]
I was adding one month to the end time, not 30d. Fixed. Thanks again for the report.
